axiomhq/axiom-go

README.md
=> Fix gopkg badge

.github/workflows/go.yml, axiom/datasets.go, axiom/datasets_test.go
This PR does two things:
1. It adds a missing field. This was detected by the CI run of PR #10.
2. It puts CI on a schedule (once a day) so we detect those kinds of issues even if no PRs are pending.
=> Fix typehint and schedule ci

axiom/axiom.go, axiom/axiom_test.go, axiom/client.go, axiom/client_test.go, axiom/users_integration_test.go
* Returns an error, if an ingest-only token is used for non-ingest operations
* Adds two new, public helper methods for identifying tokens
* Adds a new client option for setting the access token.
=> Handle ingest-only token for non-ingest endpoints

axiom/monitors_test.go, axiom/query/query.go
This change was part of the Axiom API 1.9 release.
Will tag v0.2.0 release soon after merge.
=> Add IncludeCursor field to query request

adapters/apex/apex_test.go, adapters/logrus/logrus_test.go, adapters/zap/zap_test.go, axiom/datasets_test.go
As of Go 1.16, `ioutil.ReadAll` just calls `io.ReadAll`.
=> Replace all ioutil.ReadAll calls with io.ReadAll

.github/workflows/pr.yml, .github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/server-regression.yml, README.md, axiom/client_integration_test.go, axiom/datasets_integration_test.go, axiom/monitors_integration_test.go, axiom/starred_integration_test.go, axiom/users_integration_test.go, axiom/vfields_integration_test.go
* Support the latest two Go releases and properly test against them
* Only update coverage and and code quality report from tests that ran the latest Go release
* Introduce `AXIOM_DATASET_PREFIX` as in `axiom-node` to uniquely identify a test dataset if it should be left over
* Skip Go installation for the `lint` action
* Use `github.token` instead of `secrets.GITHUB_TOKEN`. The reason for this is that to unexperienced users it looks like `GITHUB_TOKEN` is configured as a repository secret like all the other secretes for the `secrets.*` key. This makes it a bit more implicit, where the token comes from.
* Run regression test at night
* Some README fixes
=> Improved testing

axiom/client_integration_test.go, axiom/datasets.go, axiom/datasets_test.go, axiom/doc.go, axiom/notifiers.go, axiom/notifiers_test.go, axiom/orgs.go, axiom/orgs_test.go, axiom/starred.go, axiom/starred_test.go, axiom/vfields.go, axiom/vfields_integration_test.go, axiom/vfields_test.go
This change is going to be part of the Axiom API 1.10 release.
Will tag v0.4.0 upon AxiomDB release.
=> Drop VirtualField Alias field

.github/workflows/pr.yml, .github/workflows/push.yml, .github/workflows/server_regression.yml, .github/workflows/test_examples.yml, README.md, adapters/apex/apex.go, adapters/apex/apex_test.go, adapters/logrus/logrus.go, adapters/logrus/logrus_test.go, adapters/zap/zap.go, adapters/zap/zap_test.go, axiom/client.go, axiom/client_integration_test.go, axiom/client_test.go, axiom/doc.go, axiom/example_test.go, axiom/tokens_integration_test.go, examples/README.md, examples/apex/main.go, examples/ingestfile/main.go, examples/logrus/main.go, examples/zap/main.go
This updates the package to use a single constructor for the `Client` and `adapter/*` types. Configuration is now retrieved from the environment if not specified otherwise. This rougly matches what the AWS SDK does. This reduces a lot of code duplication and confusion we had in place for supporting Axiom Cloud and Selfhost.
=> Improved Client and Adapter creation

axiom/axiom.go, axiom/axiom_test.go, axiom/client.go
This adds two methods:
* `IsTokenValid` makes sure an access token has any valid Axiom prefix
* `ValidateEnvironment` makes sure client creation based on the environment works, without creating one
=> Improve client options

axiom/axiom.go, axiom/axiom_integration_test.go, axiom/client.go, axiom/client_integration_test.go, axiom/client_test.go, axiom/tokens.go
* New `ValidateCredentials` method to let users validate the client configuration before making calls or knowing any internals of which methods to use for validating different types of tokens
* Improve regex that only matches ingest-token enabled endpoints
=> Validate credentials

axiom/datasets_integration_test.go, axiom/query/result.go
Proper datatype and name for a field on the result aggregation.
Closes #71.
Will tag a patch release upon merge.
=> Fix result aggregation

README.md, axiom/axiom_test.go, axiom/client.go, axiom/client_test.go, examples/apex/main.go, examples/ingestfile/main.go, examples/logrus/main.go, examples/query/main.go, examples/zap/main.go
* Ignore the organization id when using an ingest token
* This changes some tests as the order in which the options are checked has changed. Thus, a different error is raised in some cases. But I prefer the new order since pointing out a missing access token is more obvious than pointing out a missing organizatio id.
=> Ignore organization id when using ingest tokens

README.md, axiom/axiom_integration_test.go, axiom/client_integration_test.go, axiom/orgs.go, axiom/orgs_integration_test.go, axiom/orgs_test.go, axiom/version_integration_test.go, axiom/version_test.go
Properly implement support for the upcoming shared access tokens by accepting the `keys` field.
This fixes https://github.com/axiomhq/axiom-go/runs/4755775103?check_suite_focus=true.
=> Support signing keys for organizations

axiom/error_integration_test.go, axiom/tokens_integration_test.go
This takes the API change into account, that prevents API tokens from being created without scopes or permissions.
=> Enhanced token tests

axiom/client.go, axiom/client_test.go
With the recent changes related to the outphasing of ingest tokens, there was an oversight with how we deal with **api** tokens when using the `SetNoEnv()` option. This fixes a case where an error would be returned when no organization ID was provided.
The logic is kinda tricky for something that should actually be simple because it takes into account what kind of Axiom deployment is being used as well as the type of token.
=> Allow explicit configuration with api token

Makefile, axiom/apl/format.go, axiom/datasets.go, axiom/datasets_integration_test.go, axiom/datasets_test.go, axiom/monitors.go, axiom/notifiers.go, axiom/orgs.go, axiom/query/aggregation.go, axiom/query/filter.go, axiom/query/kind.go, axiom/query/result.go, axiom/starred.go, axiom/tokens.go, axiom/users.go
<strike>This has long been outstanding but went unnoticed: There has been a new `/_info` endpoint for a while, now. This is basically a list of dataset infos as returned by a normal call to `:id/info`. The `/_stats` call shares the same response model, apart from omitting the fields so this was never an issue. But it is desirable to have the separate call available.
I was able to refactor this slightly to compensate for the missing fields and enhanced the documentation along the way.</strike>
<strike>As explained by @mhr3, the `/_info` endpoint is deprecated and - after discussion - will be replaced by `/_fields`. The rest of the information that could be obtained through `/_info` is still available through `/_stats`. The recent commit accounts for that change but I kept the improvements …
=> Add support for '/_fields' endpoint

.github/workflows/pr.yaml, .github/workflows/push.yaml, .github/workflows/server_regression.yaml, .github/workflows/test_examples.yaml, axiom/datasets.go
This PR "swallows" the new `fieldsMeta` and `fieldsMetaMap` response objects. There is no need for them to be supported in this client library, yet. But this PR makes CI green again and documents, that the fields are there but unused.
=> Swallow fields meta

axiom/client.go
This extracts the module info from the build info of a binary and uses the `axiom-go` module version in the `User-Agent` header.
I tested this manually, haven't figured out how to write a test for this. Tests are still part of this module, so it won't recoginze `axiom-go` as a dependency, even if imported.
=> feat(client): extract module info from build info for use in 'User-Agent' header

.goreleaser.yaml
We use that for most of our non-Go projects as well.
=> feat(ci): use GitHub release notes generation API for changelog

axiom/query/aggregation.go, axiom/query/aggregation_string.go, axiom/query/aggregation_test.go
This PR adds three new aggregations to `axiom-go`:
* `argmin`
* `argmax`
* `makeset`
=> feat(query): add argmin, argmax and set aggregations

adapters/apex/apex_test.go, axiom/client.go, axiom/datasets.go, axiom/datasets_test.go, axiom/options.go, axiom/orgs.go, axiom/query/aggregation.go, axiom/query/aggregation_string.go, axiom/query/aggregation_test.go, axiom/query/filter.go, axiom/query/result.go, axiom/sas/filter.go
This PR introduces `any` over `interface` and changes the order of one aggregation operation into the correct comment group.
=> chore: code grooming

axiom/client.go, axiom/client_options.go, axiom/client_test.go, axiom/limit.go, axiom/limit_string.go
This PR drops client side rate limiting. As the Axiom service has evolved, different kinds of limits have been introduced and make implementing client-side limiting harder. As we are a service that - by nature - deals with a high volume of incoming data, we decided to not let the client deal with limiting, too, as a faulty limiting logic can prevent the client from sending data (where as the server might not apply the same limit).
=> fix(limit): drop faulty rate limiting logic

adapters/apex/apex.go, adapters/apex/apex_integration_test.go, adapters/apex/apex_test.go, adapters/logrus/logrus.go, adapters/logrus/logrus_integration_test.go, adapters/logrus/logrus_test.go, adapters/zap/zap.go, adapters/zap/zap_integration_test.go, adapters/zap/zap_test.go, axiom/client_test.go, axiom/datasets_test.go, axiom/orgs_test.go, axiom/users_test.go, internal/test/adapters/doc.go, internal/test/adapters/integration.go, internal/test/adapters/unit.go, internal/test/testdata/doc.go, internal/test/testhelper/doc.go
This PR performs mostly code grooming. It resolves some outstanding `TODOs`, improves GoDoc, makes testing for adapters simpler and does some smaller cleanups in test files.
Needs #141.
=> Test cleanups

axiom/client.go, axiom/client_export_test.go, axiom/client_test.go, axiom/datasets.go, axiom/options.go, axiom/orgs.go, axiom/response.go, axiom/users.go
This exports some more client methods and functions to allow for the client to be used for self-constructed requests.
=> More exports

axiom/client.go, axiom/client_test.go, axiom/datasets.go, axiom/datasets_test.go
This PR fixes the http retry mechanism for stream-based ingest methods by properly setting `http.Request.GetBody` as well as utilizing it. This does not apply to user-supplied streams on `client.Datasets.Ingest`, although Go will do some magic if the passed `io.Reader` is one of `bytes.Buffer`, `bytes.Reader` or `strings.Reader`.
=> fix: correct http request retry for streams

adapters/apex/apex.go, adapters/apex/apex_test.go, adapters/logrus/logrus.go, adapters/logrus/logrus_test.go, axiom/datasets.go, axiom/datasets_test.go, axiom/ingest/status.go, examples/ingesthackernews/main.go
This PR adds batching support for the `IngestChannel` method. This reduces the possibility for opening connections that are open for a very long time and allows for batches to be automatically retried in case of http error.
The batching mechansim is relatively naive but should be good enough.
=> IngestChannel batching

.github/workflows/test_examples.yaml, README.md, axiom/auth/doc.go, axiom/axiom_test.go, axiom/client.go, axiom/client_export_test.go, axiom/client_integration_test.go, axiom/client_options.go, axiom/client_test.go, axiom/datasets.go, axiom/doc.go, axiom/error_integration_test.go, axiom/ingest/options.go, axiom/otel/trace.go, axiom/otel/trace_config.go, axiom/otel/trace_test.go, examples/ingestevent/main.go, examples/ingestfile/main.go, examples/ingesthackernews/main.go, internal/config/config.go, internal/config/config_test.go, internal/config/error.go, internal/config/option.go, internal/test/adapters/integration.go, internal/test/adapters/unit.go
This PR improves the documentation and examples:
* Rename occurences of "access token" -> "token"
* Improve GoDoc on specifying a timestamp
* Improve examples on specifiying a timestamp
* Improve README on specifying a timestamp
* Improve README by specifying correct import path
* Improve GoDoc by giving an example on configuration options
* General doc fixes by aligning wording
Closes #169.
=> Improve documentation

README.md, adapters/apex/apex.go, adapters/logrus/logrus.go, adapters/zap/zap.go, axiom/client.go, axiom/client_test.go, examples/ingestevent/main.go, examples/ingestfile/main.go, examples/ingesthackernews/main.go, examples/query/main.go, examples/querylegacy/main.go
This PR adds aliases for ingest and query methods on the `Client`. It is just an alias and uses the implementation on the `DatasetsService` but it keeps the full GoDoc comment for ease-of-use with autocomplete functionality.
=> Top-level aliases for ingest and query methods

axiom/datasets.go
In preparation for the new tabular result format, the "legacy" query response got a new field denoting the response as "legacy".
This "unbreaks" the scheduled CI job.
=> fix: ignore field added to legacy query response

axiom/datasets_integration_test.go
This assertion was faulty and in the future `blocksExamined` will be dropped from the API, anyways.
=> fix(test): ignore 'blocksExamined' in query result status

.github/workflows/pr.yaml, .github/workflows/push.yaml, .github/workflows/release.yaml, .github/workflows/server_regression.yaml, .github/workflows/test_examples.yaml
This PR now tests against our staging environment, as well. Examples are now only tested against staging. The server regression workflow also runs against both environments.
The PR includes some changes to concurrency groups to make sure we only ever run on job per environment. It also makes sure external contributions are not blocked by pending jobs (as secrets are not passed to forks) as we run the unit tests instead.
I also added more comments with explanations throughout the workflow files.
=> chore(ci): test against staging env

adapters/apex/apex_test.go, axiom/query/result.go, axiom/query/result_string.go, axiom/query/result_test.go, axiom/querylegacy/result.go, axiom/querylegacy/result_string.go, axiom/querylegacy/result_test.go, go.mod, go.sum, internal/test/testhelper/json.go
A Discord community user reported a failed CLI query. It became clear that the failure was caused by Axiom Go not being able to decode the query response because of an unknown message code (compiler warning).
This adds a generic code for compiler warnigns (they all start with `apl_`) as they are dynamic but most of the changes are in place to support/enhance unit testing.
It can be debated if this approach still makes sense for dynamically created message codes but this PR only fixes the error observed.
In the future we might have a `map[Code]Message` where `Code` is just any string error code.
=> fix(query): support compiler warning message codes

axiom/ingest/options.go, axiom/query/options.go
=> doc(ingest,query): better go doc on variables, labels and cursors

adapters/apex/apex.go, adapters/logrus/logrus.go, adapters/slog/slog.go, adapters/zap/zap.go, axiom/client.go, axiom/datasets.go, axiom/otel/trace.go, internal/config/config.go
Just a simple quality of life improvent that prevents users from cauing a panic when accidentally passing `nil` as a configuration option.
=> chore(options): don't panic when 'nil' is passed as an option

.github/workflows/dependent_pr.yaml
We require the check but the action is a nop when triggerd by Dependabot. So we have to create the required check, manually.
=> chore(ci): create expected 'Dependent Issues' on Dependabot PRs

adapters/slogx/slog_integration_test.go
The `slog` and `slogx` adapter packages are 100% the same code but share different imports (as `slog` just recently became part of the stdlib in Go 1.21).
But the same adapter name causes the integration test to fail as the dataset name for the test is dereived from the adapter name.
So just making sure we have unique names, here.
=> fix(slogx): adapter name

axiom/client_options.go
One of the nice features of the OTEL SDK for Go is, that - once configured - tracers are globally available. This way Axiom Go will be traced once a package user decides to setup OTEL.
However, this also means the client will be traced in that case, even if not explicitly wanted by the user. The new `NoTracing()` option sets a `noop` tracer on the client to disable this behaviour.
=> feat(client): option to disable tracing

axiom/client.go
A canceled context is permanent.
=> axiom: client: don't retry context.Canceled errors

README.md
Small addition to the `README` that explains where to find the organization id.
Closes #290.
=> docs(readme): better explain where to find the organization id

axiom/monitors.go
Have removed `err = fmt.Errorf("unknown comparison %q", s)`, as UI will contain some operators not present in this library and it saves breaking the integration specs.
=> chore(monitors): updated monitors to pass in resolvable flag which is required by the API

adapters/apex/apex.go, adapters/apex/apex_test.go, adapters/logrus/logrus.go, adapters/logrus/logrus_test.go, adapters/slog/slog.go, adapters/slog/slog_test.go, adapters/zerolog/zerolog.go, adapters/zerolog/zerolog_test.go, axiom/client.go, axiom/datasets.go
1k is pretty conservative so we increase the default batch size to 10k.
I also dropped the tests that were validating batching behaviour for all the adapters that are based on `IngestChannel()`, which has it's own set of tests in the library to make sure it batches as intended.
=> feat: increase default batch size from 1k to 10k

axiom/annotations_integration_test.go, axiom/datasets.go, axiom/datasets_integration_test.go, axiom/monitors.go, axiom/monitors_integration_test.go, axiom/notifiers.go, axiom/notifiers_integration_test.go, axiom/users.go
As part of reviewing #320 I discovered two quirks, mostly coming from copy&paste over the years:
1. `url.JoinPath` had some unnecessary params being passed in
2. The integration test suits had a couple of quirks regarding their usage
=> chore/fix: integration test suits cleanups + 'url.JoinPath' cleanups

axiom/notifiers.go
The pagerduty token is not required for out pagerduty notifier.
We're removing the need for the token from the api
=> Remove the pagerduty token field

adapters/README.md
Adding the Zerolog adapter in the README.md to make it obvious it is supported.
=> docs: Add Zerolog mention in the README.md

adapters/zerolog/README.md
The readme in the zerolog adapter is not quite idiomatic. It does not [separate logs by environment](https://axiom.co/docs/reference/datasets#separate-by-environment). It uses a non-existing function `WithDatasetName` instead of `adapter.SetDataset`. This PR addresses these issues.
=> Idiomatic zerolog adapter readme

.github/workflows/pr.yaml, .github/workflows/push.yaml, .github/workflows/server_regression.yaml, .github/workflows/test_examples.yaml, adapters/apex/apex_example_test.go, adapters/apex/apex_integration_test.go, adapters/logrus/logrus_example_test.go, adapters/logrus/logrus_integration_test.go, adapters/slog/slog_example_test.go, adapters/slog/slog_integration_test.go, adapters/zap/zap_example_test.go, adapters/zap/zap_integration_test.go, adapters/zerolog/zerolog_example_test.go, examples/apex/main.go, examples/logrus/main.go, examples/slog/main.go, examples/zap/main.go, examples/zerolog/main.go
This PR does a couple of things to fix the partly broken `test_examples.yaml` workflow:
* Replaces the deprecated (and in more recent versions of CLI also deleted) `axiom dataset info` call with `axiom query`
* Uses a dynamic `timestamp` value for the `ingestfile` test
* Flushes the writer for the `zerolog` adapter example
* Bumps Axiom CLI to the most recent version
=> .github/workflows: replace deprecated 'axiom dataset info' with 'axiom query' to verify test

axiom/client.go, axiom/monitors.go, axiom/monitors_string.go, axiom/notifiers.go, axiom/tokens.go, axiom/vfields.go, axiom/vfields_integration_test.go, axiom/vfields_test.go
Added virtual fields and tests to the client in preparation for: https://github.com/axiomhq/axiom/pull/12127 landing on production
=> feat: virtual fields to client

axiom/monitors.go, axiom/monitors_integration_test.go, axiom/monitors_string.go, axiom/monitors_test.go
=> feat(monitors): added missing monitor fields to client lib

axiom/client_options.go
Properly document that the underlying HTTP client used by default is equipped with a transport that is OTel enabled, even is `SetNoTracing` is provided. Users are expected to set their own client if they wish to prevent this.
=> chore: upgrade dependencies

adapters/slog/slog.go, adapters/slog/slog_test.go
Added the "AddSource" option to the slog adapter to better replicate the behavior of the default handler.
Since the slog.Record.source() method is private, I had to replicate its functionality.
I also didn't want to mess with the original "setup" method on the test so i created my own "setupWithSource"
=> Add source on slog adapter

adapters/apex/apex.go, adapters/logrus/logrus.go, adapters/slog/slog.go, adapters/zerolog/zerolog.go, axiom/datasets.go
This makes sure our adapters never stop logging, even if they continuously hit errors.
Food for thought: Maybe this design means we should add error callback handlers so consumers have a chance to act on errors.
=> adapters: always loop until explicitly closed

adapters/slog/slog.go, adapters/slog/slog_test.go
This PR adds special handling for error values in the slog adapter to ensure their error messages are used.
Previously, when sending an error as an Any value, it would be converted into an empty map[string]interface{}. This caused the value to be ignored by Axiom.
To address this, I added a special case to handle values that are instances of error, similar to how the std [JSONHandler](https://github.com/golang/go/blob/master/src/log/slog/json_handler.go) handles them.
i get that this somewhat breaks the flow of the code and the user can easily resolve this by explicitly writing:
```go
slog.String("error",err.Error())
```
instead of
```go
slog.Any("Error",err)
```
But in my option this gets annoying to do pretty quick
There is an argument to be made that the entire `addAttrToEvent` …
=> chore: use error message as value on slog adapter
