README.md

@lukasmalkmus kindly review and merge.

Fix license date `2021`

---

adapters/README.md
adapters/apex/apex.go
adapters/apex/apex_test.go
examples/README.md
examples/apex/main.go
go.mod

A simple apex adapter, works the same as the logrus one.

Apex adapter

---

axiom/doc.go

Taking the correct branch and folder name into account :)

Fix link to examples in GoDoc

---

README.md

quick fix on readme

---

axiom/datasets.go
axiom/datasets_test.go

This needs server side support, first. Possibly Axiom 1.6, possibly later.

CSV delimiter support

---

axiom/datasets_test.go
axiom/query/options.go
axiom/query/result.go
axiom/query/result_test.go

Adds support for Axiom 1.6 partial query improvements.

Continuation Token support

---

README.md

fix on typo

---

axiom/datasets.go
axiom/datasets_test.go

This change was part of the Axiom API 1.9 release.
Will tag v0.2.0 release soon after merge.

Add 'who' field to Dataset type

---

.github/workflows/dependent_pr.yml

Support for PR dependencies.
Needs #37.

Dependent PRs

---

.github/workflows/server_regression.yml
.github/workflows/test_examples.yml

This test all the Go code examples inside `./examples/...` by running the respective `main.go` file.

Test examples in CI

---

Makefile
axiom/client_integration_test.go
axiom/dashboards_integration_test.go
axiom/datasets_integration_test.go
axiom/monitors_integration_test.go
axiom/notifiers_integration_test.go
axiom/orgs_integration_test.go
axiom/starred_integration_test.go
axiom/teams_integration_test.go
axiom/tokens_integration_test.go
axiom/users_integration_test.go
axiom/version_integration_test.go
axiom/vfields_integration_test.go
go.mod
tools.go

Go 1.17 enhancements

---

Makefile
axiom/axiom_test.go
axiom/client.go
axiom/client_integration_test.go
axiom/client_test.go

Fixes an issue that caused cloud config to not be derived from the environment, correctly.

Fix env config

---

.github/workflows/test_examples.yml
adapters/zap/zap.go
examples/apex/main.go
examples/ingestfile/main.go
examples/logrus/main.go
examples/query/main.go
examples/zap/main.go

Test that the ingested data is present. This has the nice side effect of testing the `query` example as well.

Test more examples

---

.github/workflows/test_examples.yml
axiom/monitors.go
axiom/monitors_test.go

This supports two new monitor fields arriving **after** Axiom 1.14.

Support updated Monitors API

---

README.md
axiom/axiom.go
axiom/axiom_test.go
axiom/client.go
axiom/client_test.go
axiom/tokens.go
axiom/tokens_integration_test.go
axiom/tokens_test.go

Support for new, scoped API tokens. Needs backend PR to land.
TODO:

API Tokens

---

axiom/datasets.go
axiom/datasets_integration_test.go
axiom/datasets_test.go

This is an Axiom 1.15 feature that needs some server side additions to make the tests pass and this PR legit.

Support "Update Dataset Fields" API

---

axiom/client.go
axiom/error.go
axiom/error_integration_test.go

Simplify error struct

---

.github/workflows/pr.yml
adapters/apex/apex_integration_test.go
adapters/apex/apex_test.go
adapters/doc.go
adapters/logrus/logrus_integration_test.go
adapters/logrus/logrus_test.go
adapters/testsuite.go
adapters/zap/zap.go
adapters/zap/zap_integration_test.go
adapters/zap/zap_test.go
axiom/client_test.go
axiom/tokens_integration_test.go
examples/README.md

This PR introduces integration tests for adapters, some fixes for adapters as well as some test fixes. Don't ask :)

Improved adapter tests

---

.github/workflows/pr.yml
.github/workflows/push.yml
.github/workflows/server_regression.yml
.github/workflows/test_examples.yml
adapters/apex/apex.go
adapters/logrus/logrus.go
adapters/zap/zap.go
axiom/client.go
axiom/client_test.go

Run pr intgration tests on cloud dev as well

---

.github/workflows/pr.yml
.github/workflows/push.yml
.github/workflows/test_examples.yml

Improve some actions so we don't have to mark every job as explicitly required.

Action fixes

---

.github/workflows/pr.yml
axiom/apl/result.go
axiom/datasets_integration_test.go
axiom/datasets_test.go

An enhanced version of the APL response will contain the list of datasets the APL query covered.

APL result with dataset names

---

axiom/client.go
axiom/error.go

Proper error for the rate limiting.

Rate limit reached error

---

axiom/client.go
axiom/client_test.go
go.mod
go.sum

This PR will track the progress of the implementation of [backoff](https://github.com/cenkalti/backoff) into axiom-go.

Initial implementation of backoff

---

.github/workflows/test_examples.yaml
README.md
examples/README.md
examples/ingestevent/main.go

docs: how to ingest events

---

axiom/limit.go

Account for large integer values in the limit.

fix(limit): account for large integer values

---

axiom/query/query_test.go
axiom/query/result.go
axiom/query/result_test.go

This adds two missing fields.
It also improves some tests aroud the affected struct.

feat(query): add {min/max}Cursor to the query result status

---

axiom/auth/doc.go
axiom/query/aggregation.go
axiom/query/aggregation_string.go

Add the `makesetif` aggregation.

Add 'makesetif' aggregation

---

axiom/auth/auth.go
axiom/auth/auth_test.go
axiom/auth/pkce/pkce.go

fix(auth/pkce): code grooming

---

axiom/datasets.go
axiom/datasets_test.go

@lukasmalkmus or would you rather I remove the whole `TrimResult`?

Mark BlocksDeleted as deprecated

---

adapters/apex/doc.go
adapters/doc.go
adapters/logrus/doc.go
adapters/zap/doc.go

Improved GoDoc for the `adapters` package.

chore(adapters): better godocs

---

.github/workflows/pr.yaml
.github/workflows/test_examples.yaml

Prepare CI for https://github.com/axiomhq/axiom-go/pull/157 to pass.

fix(ci): do not run integration tests from forks

---

axiom/querylegacy/aggregation.go
axiom/querylegacy/aggregation_string.go

Add the `makelist` aggregation to the `querylegacy` package.

feat(query): add 'makelist' aggregation

---

.github/workflows/server_regression.yaml
.github/workflows/test_examples.yaml

Fix some `if` conditions and make sure example tests will not run from forks.

fix(ci): do not run example tests on forks

---

axiom/querylegacy/aggregation.go
axiom/querylegacy/aggregation_string.go

This adds more `if` aggregations to the `querylegacy` package.

feat(querylegacy): add more '[...]if' aggregations

---

.github/workflows/pr.yaml
.github/workflows/test_examples.yaml

Fixes an annoying GitHub warning (and makes sure Ci still works int eh future :))

fix(ci): update outdated action

---

README.md
axiom/client.go

fix(doc): typos

---

axiom/client_export_test.go
axiom/datasets.go
axiom/datasets_integration_test.go
axiom/datasets_test.go
axiom/ingest/options.go
axiom/options.go

Support for event labels that are applied on every event that is part of the ingest request.

feat(datasets): support event labels

---

axiom/datasets.go
axiom/orgs.go
axiom/users.go
internal/test/testhelper/env.go

This PR utilises Go 1.19 features.

Utilise Go 1.19 features

---

axiom/datasets_integration_test.go
axiom/query/options.go
axiom/query/result.go

Fixes integration tests and and GoDoc on cursors in APL.

fix(apl/test): cursors

---

.github/workflows/pr.yaml
.github/workflows/push.yaml
.github/workflows/server_regression.yaml
.github/workflows/test_examples.yaml
axiom/otel/doc.go
axiom/otel/trace.go
axiom/otel/trace_integration_test.go
axiom/otel/trace_test.go
examples/otelinstrument/main.go
examples/oteltraces/main.go
internal/test/adapters/integration.go

The (not yet publicly available) OTEL traces feature will see some changes before it goes live. This PR accounts for the changes (mainly having to specify the target dataset to use).

feat(otel): cleanups

---

.github/workflows/pr.yaml
.github/workflows/push.yaml
.github/workflows/server_regression.yaml
.github/workflows/test_examples.yaml

A simpler pattern that safes us some lines in the already large matrix.

chore(ci): simpler matrix

---

.github/workflows/dependent_pr.yaml
Makefile
axiom/client.go
axiom/orgs.go
axiom/orgs_string.go
axiom/orgs_test.go

* Rename `hobby` plan to `personal`
* Some code grooming

Rename hobby -> personal

---

adapters/apex/README.md
adapters/logrus/README.md
adapters/slog/README.md
adapters/zap/README.md

The same typo @ProZsolt fixed in  #241 is present in the individual READMEs for each adapter.

fix(adapters): readme code examples

---

README.md
adapters/README.md
adapters/apex/README.md
adapters/logrus/README.md
adapters/slog/README.md
adapters/slogx/README.md
adapters/zap/README.md
examples/README.md

@bahlo Something for you. I like the overall cleaner look instead of using emojis.

chore: readme grooming

---

.github/workflows/release.yaml
axiom/limit_test.go
axiom/orgs_test.go
axiom/query/result_test.go
axiom/querylegacy/aggregation_test.go
axiom/querylegacy/filter_test.go
axiom/querylegacy/kind_test.go
axiom/querylegacy/result_test.go
axiom/users.go
axiom/users_string.go
axiom/users_test.go

With custom role support coming up, let's have the client not error on those :) Also adds support for the `none` role.
I found some missing tests and did some code grooming on existing ones.
Also made the release workflow repsect the goreleaser version.

Custom role fix

---

.github/workflows/test_examples.yaml
axiom/client_integration_test.go

Some mini fixes for CI tracing.

fix(ci): tracing

---

axiom/monitors.go
axiom/notifiers.go

☝️ 
This now fixes all the integration tests.

fix(monitors): added missing fields that exist in the API

---

axiom/datasets_test.go

fix: linting

---

axiom/annotations.go
axiom/annotations_integration_test.go
axiom/annotations_test.go
axiom/client.go

This adds support for Annotations: https://axiom.co/docs/restapi/endpoints/getAnnotations

feat: Add AnnotationsService

---

Makefile
adapters/zerolog/zerolog.go
axiom/axiom.go
axiom/client.go
axiom/client_integration_test.go
axiom/monitors.go
axiom/orgs.go
axiom/tokens.go
axiom/tokens_integration_test.go
axiom/tokens_test.go
axiom/users.go
axiom/users_test.go

Some code gromming as the result of me diving a bit more into the codebase recently.

chore: code grooming

---

axiom/client.go

Some more sane timeout values.
Closes #332.

chore(client): increase timeouts

---

adapters/apex/apex.go
adapters/logrus/logrus.go
axiom/querylegacy/query_test.go

Ran `go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./...`.

chore: run modernize

---

axiom/query/aggregation.go
axiom/query/aggregation_string.go
axiom/query/aggregation_test.go

Some aggregations wer outdated or unsupported.

axiom/query: sync aggregations

---

axiom/monitors.go
axiom/monitors_integration_test.go
axiom/monitors_string.go

fix(typo): switch anonaly to anomaly

---

axiom/datasets.go
axiom/datasets_test.go

This PR/branch is a dependency of https://github.com/axiomhq/terraform-provider-axiom/pull/64

Axiom/Datasets: Add `UseRetentionPeriod` & `RetentionDays` to the `DatasetCreateRequest` & `DatasetUpdateRequest` structs
